services:
  - type: web
    name: my-flask-app
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y build-essential gcc && \
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: AWS_ACCESS_KEY_ID
        value: AKIAVRUVQQJ5NZBR33FC
      - key: AWS_SECRET_ACCESS_KEY
        value: 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
      - key: AWS_DEFAULT_REGION
        value: us-east-1
